services:
  db_postgres:
    image: postgres
    container_name: db_postgres
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env.test

  app:
    container_name: app
    build: .
    ports:
      - 5001:5000
    depends_on:
    - db_postgres
    env_file:
      - .env.test